apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox:1.35.0
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    env:
      - name: API_USERNAME
        valueFrom:
          secretKeyRef:
            name: hello-sm-02
            key: username
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: hello-sm-02
            key: password
  restartPolicy: Always