apiVersion: apps/v1
kind: Deployment
metadata:
 name: hpa-demo-deployment
spec:
 selector:
   matchLabels:
     run: hpa-demo-deployment
 replicas: 4
 template:
   metadata:
     labels:
       run: hpa-demo-deployment
   spec:
     containers:
     - name: hpa-demo-deployment
       image: k8s.gcr.io/hpa-example
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: "500m" # High CPU limit
           memory: "2Gi"  # High memory limit
         requests:
           cpu: "200m" 
           memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
 name: hpa-demo-deployment
 labels:
   run: hpa-demo-deployment
spec:
 ports:
 - port: 80
 selector:
   run: hpa-demo-deployment

# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#  name: hpa-demo-deployment
# spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: hpa-demo-deployment
#  minReplicas: 1
#  maxReplicas: 5
#  targetCPUUtilizationPercentage: 50