apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-ebs-test01
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3  # EBS volume type (General Purpose SSD)
  zone: ap-northeast-1a  # AWS availability zone
  encrypted: "true"  # Whether the EBS volume is encrypted or not

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-ebs-vpc-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: aws-ebs-test01 # Use the StorageClass defined above

---

apiVersion: v1
kind: Pod
metadata:
  name: ebs-pod-gp3
spec:
  containers:
  - name: ebs-container
    image: nginx:latest  # Replace with your desired image
    volumeMounts:
    - mountPath: "/data"  # Mount path inside the container
      name: ebs-volume
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: aws-ebs-vpc-claim  # Name of the PersistentVolumeClaim
